
## Answer.Create (object)
+ answer: 8 (string, required)

## Answer.Created (object)
+ id: 1 (number, required)
+ userId: 1 (number, required)
+ problemId: 1 (number, required)
+ value: 8 (string, required)
