## Problem.Create (object)
+ type: expression (string, required)
+ description: 1- (10/5)* 2 +7 (string, required)

## Problem.Created (object)
+ id: 1 (number, required)
+ userId: 1 (number, required)
+ type: expression (string, required)
+ description: 1- (10/5)* 2 +7 (string, required)
